const sidebar=document.querySelector('#sidebar');
const backdrop=document.querySelector('#sidebarBackdrop');
const titles={dashboard:'Resumen general',inventario:'Control de inventario',produccion:'Control de producción',ventas:'Gestión de ventas',caja:'Flujo de caja',reportes:'Reportes',clientes:'Directorio de clientes',empleados:'Gestión de empleados'};
function showView(id){if(!document.getElementById(id))id='dashboard';document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===id&&a.classList.contains('nav-link')));document.querySelector('#pageTitle').textContent=titles[id];sidebar.classList.remove('open');backdrop.classList.remove('show');}
document.querySelectorAll('[data-view]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const id=link.dataset.view;history.replaceState(null,'',`#${id}`);showView(id)}));
document.querySelector('#menuBtn').addEventListener('click',()=>{sidebar.classList.toggle('open');backdrop.classList.toggle('show')});backdrop.addEventListener('click',()=>{sidebar.classList.remove('open');backdrop.classList.remove('show')});
const search=document.querySelector('#inventorySearch'),filter=document.querySelector('#typeFilter');function filterInventory(){const q=search.value.toLowerCase(),type=filter.value;document.querySelectorAll('#inventoryTable tbody tr').forEach(row=>{row.hidden=!(row.textContent.toLowerCase().includes(q)&&(!type||row.children[2].textContent===type))})}search.addEventListener('input',filterInventory);filter.addEventListener('change',filterInventory);
document.querySelectorAll('.demo-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();bootstrap.Modal.getInstance(form.closest('.modal')).hide();bootstrap.Toast.getOrCreateInstance('#successToast').show();form.reset()}));
document.querySelectorAll('#quickModal [data-target]').forEach(btn=>btn.addEventListener('click',()=>setTimeout(()=>bootstrap.Modal.getOrCreateInstance(document.querySelector(`#${btn.dataset.target}`)).show(),250)));
window.addEventListener('hashchange',()=>showView(location.hash.slice(1)));showView(location.hash.slice(1)||'dashboard');
